export const JOB_TITLE_SUGGESTIONS = [
  "Software Engineer",
  "Junior Software Engineer",
  "Senior Software Engineer",
  "Staff Software Engineer",
  "Principal Software Engineer",
  "Software Development Engineer (SDE I)",
  "Software Development Engineer II (SDE II)",
  "Software Development Engineer III (SDE III)",
  "Systems Engineer",
  "Systems Development Engineer",
  "Backend Engineer",
  "Frontend Engineer",
  "Full Stack Engineer",
  "Mobile Engineer (iOS)",
  "Mobile Engineer (Android)",
  "DevOps Engineer",
  "Site Reliability Engineer (SRE)",
  "Cloud Engineer",
  "Platform Engineer",
  "Infrastructure Engineer",
  "Data Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Engineer",
  "AI/ML Research Engineer",
  "Security Engineer",
  "QA Engineer / SDET",
  "Embedded Systems Engineer",
  "Junior Java Developer",
  "Java Developer",
  "Python Developer",
  "Product Engineer",
  "Technical Lead",
  "Engineering Manager",
];
